### ISSUE TITLE
Crash after code received

### ISSUE THREAD

**Issue by josephnle** [mawie81/electron-oauth2#10]
I think this issue might be affecting this package:
https://github.com/electron/electron/issues/4374

I'm using this package with GitHub GHE OAuth. I have values set for client ID, client secret, redirect URL, token URL, and redirect URI. Currently using Electron 1.3.1

**Comment by mawie81** [comment]
I couldn´t really reproduce but just published version 2.3.1 with the proposed workaround. Could you give it another try?

**Comment by josephnle** [comment]
Works, thanks a bunch
