### ISSUE TITLE
Specify additional parameters in the token request?

### ISSUE THREAD

**Issue by HSAR** [mawie81/electron-oauth2#13]
Attempting to use electron-oauth2 with Azure Active Directory results in an error because the token request to AAD must specify the "resource" (internal terminology) that the token is to be redeemed against. This takes the form of an additional parameter in the token request, but there isn't any way to do this at the moment.

Implementation thoughts:
Since `function tokenRequest(data)` at index.js:75 does a `queryString.stringify(data)` call before sending its request, everything is in place except for a way to pass extra data into the data object.

**Comment by mawie81** [comment]
Landed with 2.4.0
