### ISSUE TITLE
BrowserWindow is not a constructor(…)

### ISSUE THREAD

**Issue by jzeni** [mawie81/electron-oauth2#15]
Hi,
I am getting this error, and I am very lost since a few days:

> Uncaught (in promise) TypeError: BrowserWindow is not a constructor(…)      Index.js:35

I would appreciate any help.

**Comment by johnf** [comment]
@jzeni try using a branch which has #11 in it

**Comment by jzeni** [comment]
It worked!. Thank you.

Sorry for the delay.
