### ISSUE TITLE
Syntax error 'Unexpected token {'

### ISSUE THREAD

**Issue by jeffheifetz** [mawie81/electron-oauth2#8]
I'm using Node v5.9.1, but it throws a syntax error on https://github.com/mawie81/electron-oauth2/blob/master/index.js#L6.

Would it be acceptable to change it to `const BrowserWindow = require('electron').BrowserWindow;`

**Comment by mawie81** [comment]
Yeah I can do that or if you want to PR feel free 😄

**Comment by jeffheifetz** [comment]
I've opened #9 to address this

**Comment by mawie81** [comment]
Thanks for the PR! Just merged it and published as 2.3.0
